name: Musings About Life and Work
favicon: null
layout_spectrum: 0.8133188616484404
typography_spectrum: 0.13979919021949172
title: About Life and Work
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050511'
    - '#987b6b'
    - '#755441'
    - '#f2d5c5'
    - '#822726'
  brandStrength: 1
  lightness: 1
  saturation: 0.017288681818172336
  rhythmicContrast: 1
purpose: []
