typography_spectrum: 0.7381076388464005
color:
  saturation: 0.2982164286326912
  brandStrength: 0.2736016972067001
  lightness: 0.8531286462574349
  brandColors:
    - '#FFFFFF'
    - '#2D3E50'
    - '#E84C3D'
    - '#297FB8'
    - '#CACACA'
  rhythmicContrast: 0.2655436428087662
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/547edcbf-52e9-4e48-9cb6-438fc34b63ab.jpg
  type: null
  appId: null
layout_spectrum: 0.6760260822318753
analytics:
  twitter: nvkib
  google: UA-85477580-1
  facebook: '1758800244380958'
author:
  name: Faun deHenry
  email: info@dehenry.co
  url: 'http://dehenry.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7623ade0-c655-4d9f-9fdf-cd836bdb57c5.jpg
name: Strategies for Your Business & Your Life
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: About Me
    id: 927e35b0-2b02-4665-a389-7121553ff1f8
    type: content
  - name: Digital Nomad Life
    id: c71ea35f-ea18-41e7-a8bd-1e24777e22b2
    type: content
  - name: Musings on Balance
    id: 2022067a-0d77-4ae6-9efb-e04a438dafe5
    type: content
  - name: Blog
    id: 4c261303-3706-4100-9b10-f2914c4c3150
    type: content
  - name: Facebook Group for Entrepreneurs & Small Business Owners
    id: dc2219be-0cfe-4e81-91d4-c0293d38ca05
    type: content
  - name: What Is Strategic Marketing?
    id: d8272aaf-37ef-4ded-9a56-8157c3936eb1
    type: content
  - name: Book An Introductory Meeting
    url: 'https://my.timetrade.com/book/56R7L'
    type: external
  - name: Digital Nomad Life 2
    id: 038bd97d-060b-4111-a539-ec54f82e4506
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/50d64d0e-7aa9-4144-bb9b-7a9e780da4ae.ico
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'About Life & Work '
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/50c232d7-92dd-45eb-b1ba-153b247fa4ad.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/50c232d7-92dd-45eb-b1ba-153b247fa4ad.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ed9dbd7e-8810-4911-9643-097d8d876004.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ed9dbd7e-8810-4911-9643-097d8d876004.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Find Your Fulcrum Between Your Life and Business
purpose:
  - type: external
    url: 'http://framework.dehenry.com/'
    label: Business Growth Framework
